x-airflow-common: &airflow-common
  build: . # Builds the Dockerfile in this folder
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_airflow/${POSTGRES_DB}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW_HOME: /opt/airflow
    PYTHONPATH: /opt/airflow:/home/airflow/.local/lib/python3.8/site-packages
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./logs:/opt/airflow/logs
    - ../processing:/opt/airflow/processing
    - ../ingestion:/opt/airflow/ingestion
    - ../data:/opt/airflow/data
    - ../spark-jars:/opt/spark-jars
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres_airflow
  networks:
    - parking-network

services:
  # Database just for Airflow metadata (NOT for parking data)
  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - parking-network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    # OVERRIDE here too
    user: root
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    # OVERRIDE the common user setting to run as root
    user: root
    command: scheduler

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}

volumes:
  airflow_db_data:


networks:
  parking-network:
    external: true
